package:
  name: mt_finder
  version: 1.0.0

source:
  git_url: https://github.com/zilov/midnax.git

requirements:
  run:
    - python
    - blast

test:
  commands:
    - midnax -h

about:
  home: https://github.com/zilov/midnax
  license: GPLv3
  summary: 'A tool to find mtRNA inside of genome'
